version: 1
disable_existing_loggers: False

formatters:
    standard:
        (): app.logging.LogFormatter
        style: "{"
        format: "{asctime} | {levelname:<8} | {alias:<8} | {prefix}{message}"
        datefmt: "%Y-%m-%d %H:%M:%S"
        colored: False
    colored:
        (): app.logging.LogFormatter
        style: "{"
        format: "{asctime} | {levelname:<8} | {alias:<8} | {prefix}{message}"
        datefmt: "%Y-%m-%d %H:%M:%S"
        colored: True

handlers:
    console:
        class: logging.StreamHandler
        formatter: colored
        stream: ext://sys.stdout
    app_file:
        class: logging.handlers.RotatingFileHandler
        formatter: standard
        filename: "instance/logs/app.log"
        maxBytes: 10_000_000
        backupCount: 3
        encoding: utf8
    daemon_file:
        class: logging.handlers.RotatingFileHandler
        formatter: standard
        filename: "instance/logs/daemon.log"
        maxBytes: 10_000_000
        backupCount: 3
        encoding: utf8
    database_file:
        class: logging.handlers.RotatingFileHandler
        formatter: standard
        filename: "instance/logs/database.log"
        maxBytes: 10_000_000
        backupCount: 3
        encoding: utf8
    redis_file:
        class: logging.handlers.RotatingFileHandler
        formatter: standard
        filename: "instance/logs/redis.log"
        maxBytes: 10_000_000
        backupCount: 3
        encoding: utf8
    maintenance_file:
        class: logging.handlers.RotatingFileHandler
        formatter: standard
        filename: "instance/logs/maintenance.log"
        maxBytes: 10_000_000
        backupCount: 3
        encoding: utf8

loggers:
    app:
        level: INFO
        handlers: [console, app_file]
        propagate: False
    beatmaps:
        level: INFO
        handlers: [ console, app_file ]
        propagate: False
    osu_api:
        level: INFO
        handlers: [ console, app_file ]
        propagate: False
    search:
        level: INFO
        handlers: [ console, app_file ]
        propagate: False
    security:
        level: INFO
        handlers: [ console, app_file ]
        propagate: False
    spec:
        level: INFO
        handlers: [ console, app_file ]
        propagate: False
    lifespan:
        level: INFO
        handlers: [ console, app_file ]
        propagate: False
    daemon:
        level: INFO
        handlers: [console, daemon_file]
        propagate: False
    database:
        level: INFO
        handlers: [console, database_file]
        propagate: False
    redis:
        level: INFO
        handlers: [console, redis_file]
        propagate: False
    setup:
        level: INFO
        handlers: [console, maintenance_file]
        propagate: False
    manage:
        level: INFO
        handlers: [ console, maintenance_file ]
        propagate: False
    migrate:
        level: INFO
        handlers: [ console, maintenance_file ]
        propagate: False
    root:
        level: WARNING
        handlers: [console]