openapi: 3.0.0

info:
    title: Test App
    description: Test API
    version: 1.0.0

servers:
    - url: /api/v1

components:
    securitySchemes:
        ApiKeyAuth:
            type: apiKey
            in: header
            name: X-API-KEY
            x-apikeyInfoFunc: app.auth.api_key_info

    schemas:
        User:
            description: A JSON object containing an osu! user ID
            type: object
            properties:
                osu_id:
                    type: integer

        Beatmap:
            description: A JSON object containing a beatmap ID
            type: object
            properties:
                beatmap_id:
                    type: integer

    parameters:
        osu_id:
            name: osu_id
            description: osu! user ID
            in: path
            required: True
            schema:
                type: integer

        beatmap_id:
            name: beatmap_id
            description: osu! beatmap ID
            in: path
            required: True
            schema:
                type: integer

        version_number:
            name: version_number
            description: osu! beatmap version ID
            in: path
            required: True
            schema:
                type: integer

    requestBodies:
        Beatmap:
            description: Beatmap to download to the server
            required: true
            content:
                application/json:
                    schema:
                        $ref: "#/components/schemas/Beatmap"

    responses:
        UnauthorizedError:
            description: X-API-KEY is missing in the header or invalid
            headers:
                WWW-Authenticate:
                    schema:
                        type: string

paths:
    /users:
        get:
            summary: Returns a list of users
            tags:
                - Users
            security:
                - ApiKeyAuth: []
            responses:
                200:
                    description: Successfully retrieved all users
                401:
                    $ref: "#/components/responses/UnauthorizedError"
                default:
                    description: Pass

    /beatmaps:
        get:
            summary: Returns a list of beatmaps stored on the server
            tags:
                - Beatmaps
            responses:
                200:
                    description: Successfully retrieved beatmaps
                default:
                    description: Pass
        post:
            summary: Downloads a new beatmap to the server
            tags:
                - Beatmaps
#            security:
#                - ApiKeyAuth: []
            requestBody:
                $ref: "#/components/requestBodies/Beatmap"
            responses:
                201:
                    description: Successfully downloaded beatmap to the server
                default:
                    description: Pass

    /beatmaps/{beatmap_id}:
        get:
            summary: Returns the metadata of the beatmap
            tags:
                - Beatmaps
            parameters:
                - $ref: "#/components/parameters/beatmap_id"
            responses:
                200:
                    description: Successfully retrieved beatmap metadata
                default:
                    description: Pass

    /beatmaps/{beatmap_id}/versions:
        get:
            summary: Returns a list of the beatmap's version IDs
            tags:
                - Beatmaps
            parameters:
                - $ref: "#/components/parameters/beatmap_id"
            responses:
                200:
                    description: Successfully retrieved beatmap versions
                default:
                    description: Pass

    /beatmaps/{beatmap_id}/versions/{version_number}:
        get:
            summary: Returns the .osu file of the beatmap's specified version
            tags:
                - Beatmaps
            parameters:
                - $ref: "#/components/parameters/beatmap_id"
                - $ref: "#/components/parameters/version_number"
            responses:
                200:
                    description: Successfully retrieved beatmap file
                default:
                    description: Pass

    /leaderboards:
        get:
            summary: Returns statistics of active leaderboards
            tags:
                - Leaderboards
            responses:
                200:
                    description: Successfully retrieved statistics
                default:
                    description: Pass

    /leaderboards/{beatmap_id}:
        get:
            summary: Returns the leaderboard of the beatmap's latest version
            tags:
                - Leaderboards
            parameters:
                - $ref: "#/components/parameters/beatmap_id"
            responses:
                200:
                    description: Successfully retrieved leaderboard
                default:
                    description: Pass

    /leaderboards/{beatmap_id}/versions:
        get:
            summary: Returns a list of the beatmap's leaderboard versions
            tags:
                - Leaderboards
            parameters:
                - $ref: "#/components/parameters/beatmap_id"
            responses:
                200:
                    description: Successfully retrieved leaderboard versions
                default:
                    description: Pass

    /leaderboards/{beatmap_id}/versions/{version_number}:
        get:
            summary: Returns the leaderboard of the beatmap's specified version
            tags:
                - Leaderboards
            parameters:
                - $ref: "#/components/parameters/beatmap_id"
                - $ref: "#/components/parameters/version_number"
            responses:
                200:
                    description: Successfully retrieved leaderboard
                default:
                    description: Pass