"""Initial schema from SQLAlchemy models

Revision ID: 3c32d58a5a27
Revises: 
Create Date: 2026-07-16 17:18:23.156303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c32d58a5a27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_audit_timestamp', 'audit_logs', [sa.literal_column('timestamp DESC')], unique=False)
    op.add_column('oauth_tokens', sa.Column('access_token_enc', sa.LargeBinary(), nullable=False))
    op.add_column('oauth_tokens', sa.Column('refresh_token_enc', sa.LargeBinary(), nullable=True))
    op.alter_column('oauth_tokens', 'expires_at',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False,
               postgresql_using='to_timestamp(expires_at)::timestamptz')
    op.drop_constraint(op.f('oauth_tokens_access_token_key'), 'oauth_tokens', type_='unique')
    op.drop_column('oauth_tokens', 'refresh_token')
    op.drop_column('oauth_tokens', 'access_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_tokens', sa.Column('access_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('oauth_tokens', sa.Column('refresh_token', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('oauth_tokens_access_token_key'), 'oauth_tokens', ['access_token'], postgresql_nulls_not_distinct=False)
    op.alter_column('oauth_tokens', 'expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.INTEGER(),
               existing_nullable=False,
               postgresql_using='extract(epoch from expires_at)::integer')
    op.drop_column('oauth_tokens', 'refresh_token_enc')
    op.drop_column('oauth_tokens', 'access_token_enc')
    op.drop_index('idx_audit_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_entity', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
