"""Initial schema from SQLAlchemy models

Revision ID: 3c32d58a5a27
Revises: 
Create Date: 2026-07-16 17:18:23.156303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c32d58a5a27'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE TABLE IF NOT EXISTS audit_logs (
            id SERIAL NOT NULL,
            timestamp TIMESTAMP WITH TIME ZONE NOT NULL,
            user_id INTEGER,
            action VARCHAR(100) NOT NULL,
            entity_type VARCHAR(50),
            entity_id VARCHAR(100),
            details JSON,
            ip_address VARCHAR(45),
            user_agent TEXT,
            PRIMARY KEY (id)
        )
    """)
    op.execute("CREATE INDEX IF NOT EXISTS idx_audit_action ON audit_logs (action)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_audit_entity ON audit_logs (entity_type, entity_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_audit_timestamp ON audit_logs (timestamp DESC)")

    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'oauth_tokens' AND column_name = 'access_token_enc'
            ) THEN
                ALTER TABLE oauth_tokens ADD COLUMN access_token_enc BYTEA NOT NULL;
            END IF;
        END $$;
    """)

    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'oauth_tokens' AND column_name = 'refresh_token_enc'
            ) THEN
                ALTER TABLE oauth_tokens ADD COLUMN refresh_token_enc BYTEA;
            END IF;
        END $$;
    """)

    op.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'oauth_tokens' AND column_name = 'expires_at'
            ) THEN
                ALTER TABLE oauth_tokens ALTER COLUMN expires_at TYPE TIMESTAMP WITH TIME ZONE
                    USING to_timestamp(expires_at)::timestamptz;
            END IF;
        END $$;
    """)

    op.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.table_constraints
                WHERE constraint_name = 'oauth_tokens_access_token_key'
                AND table_name = 'oauth_tokens'
            ) THEN
                ALTER TABLE oauth_tokens DROP CONSTRAINT oauth_tokens_access_token_key;
            END IF;
        END $$;
    """)

    op.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'oauth_tokens' AND column_name = 'refresh_token'
            ) THEN
                ALTER TABLE oauth_tokens DROP COLUMN refresh_token;
            END IF;
        END $$;
    """)

    op.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'oauth_tokens' AND column_name = 'access_token'
            ) THEN
                ALTER TABLE oauth_tokens DROP COLUMN access_token;
            END IF;
        END $$;
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'oauth_tokens' AND column_name = 'access_token'
            ) THEN
                ALTER TABLE oauth_tokens ADD COLUMN access_token VARCHAR NOT NULL;
            END IF;
        END $$;
    """)

    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'oauth_tokens' AND column_name = 'refresh_token'
            ) THEN
                ALTER TABLE oauth_tokens ADD COLUMN refresh_token VARCHAR NOT NULL;
            END IF;
        END $$;
    """)

    op.execute("""
        DO $$ BEGIN
            IF NOT EXISTS (
                SELECT 1 FROM information_schema.table_constraints
                WHERE constraint_name = 'oauth_tokens_access_token_key'
                AND table_name = 'oauth_tokens'
            ) THEN
                ALTER TABLE oauth_tokens ADD CONSTRAINT oauth_tokens_access_token_key UNIQUE (access_token);
            END IF;
        END $$;
    """)

    op.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'oauth_tokens' AND column_name = 'expires_at'
            ) THEN
                ALTER TABLE oauth_tokens ALTER COLUMN expires_at TYPE INTEGER
                    USING extract(epoch from expires_at)::integer;
            END IF;
        END $$;
    """)

    op.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'oauth_tokens' AND column_name = 'refresh_token_enc'
            ) THEN
                ALTER TABLE oauth_tokens DROP COLUMN refresh_token_enc;
            END IF;
        END $$;
    """)

    op.execute("""
        DO $$ BEGIN
            IF EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = 'oauth_tokens' AND column_name = 'access_token_enc'
            ) THEN
                ALTER TABLE oauth_tokens DROP COLUMN access_token_enc;
            END IF;
        END $$;
    """)

    op.execute("DROP INDEX IF EXISTS idx_audit_timestamp")
    op.execute("DROP INDEX IF EXISTS idx_audit_entity")
    op.execute("DROP INDEX IF EXISTS idx_audit_action")
    op.execute("DROP TABLE IF EXISTS audit_logs")
    # ### end Alembic commands ###
