"""Add search performance indexes

Revision ID: 540b96c318fb
Revises: 3c32d58a5a27
Create Date: 2026-07-16 17:23:44.390573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540b96c318fb'
down_revision: Union[str, Sequence[str], None] = '3c32d58a5a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE INDEX IF NOT EXISTS idx_beatmap_listings_snapshot ON beatmap_listings (beatmap_snapshot_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_beatmap_snapshots_beatmap_id ON beatmap_snapshots (beatmap_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_beatmapset_listings_snapshot ON beatmapset_listings (beatmapset_snapshot_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_beatmapset_snapshots_beatmapset_id ON beatmapset_snapshots (beatmapset_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_leaderboards_beatmap ON leaderboards (beatmap_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_profiles_user_id ON profiles (user_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_queue_rules_queue_active ON queue_rules (queue_id, is_active)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_requests_beatmapset ON requests (beatmapset_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_requests_queue_status ON requests (queue_id, status)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_scores_leaderboard ON scores (leaderboard_id)")
    op.execute("CREATE INDEX IF NOT EXISTS idx_scores_user_beatmap ON scores (user_id, beatmap_id)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_scores_user_beatmap")
    op.execute("DROP INDEX IF EXISTS idx_scores_leaderboard")
    op.execute("DROP INDEX IF EXISTS idx_requests_queue_status")
    op.execute("DROP INDEX IF EXISTS idx_requests_beatmapset")
    op.execute("DROP INDEX IF EXISTS idx_queue_rules_queue_active")
    op.execute("DROP INDEX IF EXISTS idx_profiles_user_id")
    op.execute("DROP INDEX IF EXISTS idx_leaderboards_beatmap")
    op.execute("DROP INDEX IF EXISTS idx_beatmapset_snapshots_beatmapset_id")
    op.execute("DROP INDEX IF EXISTS idx_beatmap_listings_snapshot")
    op.execute("DROP INDEX IF EXISTS idx_beatmap_snapshots_beatmap_id")
    op.execute("DROP INDEX IF EXISTS idx_beatmapset_listings_snapshot")
    # ### end Alembic commands ###
