"""Add search performance indexes

Revision ID: 540b96c318fb
Revises: 3c32d58a5a27
Create Date: 2026-07-16 17:23:44.390573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540b96c318fb'
down_revision: Union[str, Sequence[str], None] = '3c32d58a5a27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_beatmap_listings_snapshot', 'beatmap_listings', ['beatmap_snapshot_id'], unique=False)
    op.create_index('idx_beatmap_snapshots_beatmap_id', 'beatmap_snapshots', ['beatmap_id'], unique=False)
    op.create_index('idx_beatmapset_listings_snapshot', 'beatmapset_listings', ['beatmapset_snapshot_id'], unique=False)
    op.create_index('idx_beatmapset_snapshots_beatmapset_id', 'beatmapset_snapshots', ['beatmapset_id'], unique=False)
    op.create_index('idx_leaderboards_beatmap', 'leaderboards', ['beatmap_id'], unique=False)
    op.create_index('idx_profiles_user_id', 'profiles', ['user_id'], unique=False)
    op.create_index('idx_queue_rules_queue_active', 'queue_rules', ['queue_id', 'is_active'], unique=False)
    op.create_index('idx_requests_beatmapset', 'requests', ['beatmapset_id'], unique=False)
    op.create_index('idx_requests_queue_status', 'requests', ['queue_id', 'status'], unique=False)
    op.create_index('idx_scores_leaderboard', 'scores', ['leaderboard_id'], unique=False)
    op.create_index('idx_scores_user_beatmap', 'scores', ['user_id', 'beatmap_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_scores_user_beatmap', table_name='scores')
    op.drop_index('idx_scores_leaderboard', table_name='scores')
    op.drop_index('idx_requests_queue_status', table_name='requests')
    op.drop_index('idx_requests_beatmapset', table_name='requests')
    op.drop_index('idx_queue_rules_queue_active', table_name='queue_rules')
    op.drop_index('idx_profiles_user_id', table_name='profiles')
    op.drop_index('idx_leaderboards_beatmap', table_name='leaderboards')
    op.drop_index('idx_beatmapset_snapshots_beatmapset_id', table_name='beatmapset_snapshots')
    op.drop_index('idx_beatmap_listings_snapshot', table_name='beatmap_listings')
    op.drop_index('idx_beatmap_snapshots_beatmap_id', table_name='beatmap_snapshots')
    op.drop_index('idx_beatmapset_listings_snapshot', table_name='beatmapset_listings')
    # ### end Alembic commands ###
