"""Fixture loader for the seeding system.

Reads fixture data from instance/fixtures/ (fetched/generated by the
``manage fixtures`` commands) and adapts it into the format the seeders
expect.  This decouples the seeders from hardcoded JSON files committed
to source control.

Public API
----------
check_fixtures(targets)
    Verify that instance/fixtures/ has enough data for the requested
    seed targets.  Returns a dict with status, counts, and missing
    categories.

load_seeding_data(targets)
    Load and adapt fixture data from instance/fixtures/ for the
    requested seed targets.  Returns a dict mapping SeederTarget to
    the prepared data list.
"""
from __future__ import annotations

import json
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING

from app.config import PROJECT_ROOT
from app.database.seeding.target import SeederTarget

if TYPE_CHECKING:
    from app.database.seeding.target import SeedTarget

FIXTURES_DIR = PROJECT_ROOT / "instance" / "fixtures"


# ---------------------------------------------------------------------------
# Check
# ---------------------------------------------------------------------------


def check_fixtures(targets: set[SeederTarget]) -> dict:
    """Check whether instance/fixtures/ has enough data for *targets*.

    Returns a dict with keys:

    - ``status``: ``"ok"`` or ``"missing"``
    - ``counts``: dict of category -> number of fixture files found
    - ``missing``: list of category names that have zero fixtures
    """
    counts: dict[str, int] = {}

    # Users: count across all ruleset subdirectories
    users_path = FIXTURES_DIR / "users"
    if users_path.exists():
        counts["users"] = len(list(users_path.rglob("*.json")))
    else:
        counts["users"] = 0

    # Beatmapsets
    bms_path = FIXTURES_DIR / "beatmapsets"
    counts["beatmapsets"] = (
        len(list(bms_path.glob("*.json"))) if bms_path.exists() else 0
    )

    # Beatmap tags
    tags_path = FIXTURES_DIR / "beatmap_tags.json"
    counts["beatmap_tags"] = 1 if tags_path.exists() else 0

    # Queues / requests are auto-generatable
    counts["queues"] = 0
    counts["requests"] = 0

    # Determine which categories are actually needed
    needed: set[str] = set()
    if SeederTarget.USER in targets:
        needed.add("users")
    if SeederTarget.BEATMAP in targets:
        needed.update({"beatmapsets", "beatmap_tags"})

    missing = [cat for cat in needed if counts.get(cat, 0) == 0]

    return {
        "status": "missing" if missing else "ok",
        "counts": counts,
        "missing": missing,
    }


# ---------------------------------------------------------------------------
# Load & adapt
# ---------------------------------------------------------------------------


def load_seeding_data(targets: set[SeederTarget]) -> dict[SeederTarget, list[dict]]:
    """Load fixture data from instance/fixtures/ and adapt it for seeders.

    Returns a dict mapping each requested SeederTarget to a list of
    prepared data dicts ready to be passed to ``db.add(Model, **entry)``.
    """
    data: dict[SeederTarget, list[dict]] = {}

    if SeederTarget.USER in targets:
        data[SeederTarget.USER] = _load_users()

    if SeederTarget.BEATMAP in targets:
        data[SeederTarget.BEATMAP] = _load_beatmaps()

    if SeederTarget.QUEUE in targets:
        data[SeederTarget.QUEUE] = _load_queues()

    if SeederTarget.REQUEST in targets:
        data[SeederTarget.REQUEST] = _load_requests()

    return data


def _load_users() -> list[dict]:
    """Load users from instance/fixtures/users/{ruleset}/user_*.json.

    Adapts the flat osu! API user response into the format seeders expect:
    ``{"id": ..., "profile": {<all osu! API fields>}, "roles": [...]}``.
    """
    users_path = FIXTURES_DIR / "users"
    if not users_path.exists():
        return []

    # DateTime columns in Profile model that need conversion
    datetime_columns = {"join_date", "last_visit", "updated_at"}

    users: list[dict] = []
    for ruleset_dir in sorted(users_path.iterdir()):
        if not ruleset_dir.is_dir():
            continue
        for f in sorted(ruleset_dir.glob("user_*.json")):
            try:
                with open(f) as fh:
                    api_data = json.load(fh)
            except json.JSONDecodeError:
                continue

            user_id = api_data.get("id")
            if user_id is None:
                continue

            # Only convert known DateTime columns, not JSONB fields
            for col in datetime_columns:
                if col in api_data and isinstance(api_data[col], str):
                    try:
                        api_data[col] = datetime.fromisoformat(api_data[col])
                    except ValueError:
                        pass

            users.append({
                "id": user_id,
                "profile": api_data,
                "roles": [],
            })

    return users


def _load_beatmaps() -> list[dict]:
    """Load beatmapsets from instance/fixtures/beatmapsets/beatmapset_*.json.

    Adapts the osu! API response (which uses ``maps``) into the format
    the BeatmapSeeder expects (``beatmaps``).
    """
    bms_path = FIXTURES_DIR / "beatmapsets"
    if not bms_path.exists():
        return []

    beatmapsets: list[dict] = []
    for f in sorted(bms_path.glob("beatmapset_*.json")):
        try:
            with open(f) as fh:
                api_data = json.load(fh)
        except json.JSONDecodeError:
            continue

        # The osu! API returns "maps" but the seeder expects "beatmaps"
        if "maps" in api_data and "beatmaps" not in api_data:
            api_data["beatmaps"] = api_data.pop("maps")

        # Ensure snapshots key exists (may be empty if API didn't include them)
        api_data.setdefault("snapshots", [])

        beatmapsets.append(api_data)

    return beatmapsets


def _load_queues() -> list[dict]:
    """Load queues from instance/fixtures/queues/queue_*.json."""
    queues_path = FIXTURES_DIR / "queues"
    if not queues_path.exists():
        return []

    queues: list[dict] = []
    for f in sorted(queues_path.glob("queue_*.json")):
        try:
            with open(f) as fh:
                queues.append(json.load(fh))
        except json.JSONDecodeError:
            continue

    return queues


def _load_requests() -> list[dict]:
    """Load requests from instance/fixtures/requests/request_*.json."""
    requests_path = FIXTURES_DIR / "requests"
    if not requests_path.exists():
        return []

    requests: list[dict] = []
    for f in sorted(requests_path.glob("request_*.json")):
        try:
            with open(f) as fh:
                requests.append(json.load(fh))
        except json.JSONDecodeError:
            continue

    return requests
