Profiles:
    get:
        summary: Returns a list of profiles
        tags:
            - Profiles
        parameters:
            - $ref: "../parameters/query/sorting/profile.yaml#/ProfileSorting"
            - $ref: "../parameters/query/include/profile.yaml#/ProfileInclude"
            - $ref: "../parameters/query/limit.yaml#/Limit"
            - $ref: "../parameters/query/offset.yaml#/Offset"
            - $ref: "../parameters/query/reversed.yaml#/Reversed"
        responses:
            200:
                $ref: "../responses/200/profile.yaml#/ProfileResults"
            400:
                $ref: "../responses/400/generic.yaml#/BadRequest"
            401:
                $ref: "../responses/401/generic.yaml#/Unauthorized"

ProfileByUserId:
    get:
        summary: Returns the profile for the specified user ID
        tags:
            - Profiles
        parameters:
            - $ref: "../parameters/path/user.yaml#/UserId"
            - $ref: "../parameters/query/include/profile.yaml#/ProfileInclude"
        responses:
            200:
                $ref: "../responses/200/profile.yaml#/ProfileResult"
            400:
                $ref: "../responses/400/generic.yaml#/BadRequest"
            404:
                $ref: "../responses/404/generic.yaml#/NotFound"